version: '3.0'

services:
  btproxy:
    build:
      context: .
      args:
        MASTER_ADDRESS: ""
        SLAVE_ADDRESS: ""
    container_name: btproxy
    privileged: true
    devices:
      - "/dev/bus/usb/004/003"
      - "/dev/bus/usb/001/003"
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/run/dbus/system_bus_socket